In [1]:
# Import the required packages
import pandas as pd
from os import path

pd.set_option("display.max_rows", 300)

## 1. Import Data:

Our first task is to import all the required data tables for our goal.

We are importing following tables:

1. Country wise medal counts of the Tokyo Olympics 2020: **`Tokyo_Medals_2020.csv`**
2. Country wise medal counts of the Rio Olympics 2016: **`Rio_Medals_2016.csv`**
3. Country wise medal counts of the London Olympics 2012: **`London_Medals_2012.csv`**

4. Country wise population table: **`Population_2020-21.csv`**
5. Country wise Covid and Vaccination Data **`Covid_Vaccination_Data.csv`**
6. Country wise GDP data **`GDP_Actual_Value.csv`**

In [2]:
# full path where data files are stored
dir_path = input("Enter the directory where data files are stored: " )

Enter the directory where data files are stored: /Users/tanuja/Documents/Germany/Jacobs University, Bremen/Study Material/Fall 2021/Data Management with Python/HomeWork/DMP/Final DMP/


In [3]:
df_tokyo = pd.read_csv(path.join(dir_path,"Tokyo_Medals_2020.csv"), header=0)

df_tokyo_top = df_tokyo.head(5)
print("Tokyo Olympics 2020 data frame:\n\n{}".format(df_tokyo_top),"\n\n")

Tokyo Olympics 2020 data frame:

      Country  Gold Medal  Silver Medal  Bronze Medal  Total  Rank By Total
0   Argentina           0             1             2      3             60
1     Armenia           0             2             2      4             47
2   Australia          17             7            22     46              6
3     Austria           1             1             5      7             33
4  Azerbaijan           0             3             4      7             33 




In [4]:
df_rio = pd.read_csv(path.join(dir_path,"Rio_Medals_2016.csv"), header=0)

df_rio_top = df_rio.head(5)
print("Rio Olympics 2016 data frame:\n\n{}".format(df_rio_top),"\n\n")

Rio Olympics 2016 data frame:

     Country  Gold  Silver  Bronze
0    Algeria     0       2       0
1  Argentina     3       1       0
2    Armenia     1       3       0
3  Australia     8      11      10
4    Austria     0       0       1 




In [5]:
df_london = pd.read_csv(path.join(dir_path,"London_Medals_2012.csv"), header=0)

df_london_top = df_london.head(5)
print("London Olympics 2012 data frame:\n\n{}".format(df_london_top),"\n\n")

London Olympics 2012 data frame:

       Country  Gold Medal  Silver Medal  Bronze Medal  Total
0  Afghanistan           0             0             1      1
1      Algeria           1             0             0      1
2    Argentina           1             1             2      4
3      Armenia           0             1             1      2
4    Australia           8            15            12     35 




In [6]:
df_population = pd.read_csv(path.join(dir_path,"Population_2020-21.csv"), header= 0)

df_population_top = df_population.head(5)
print("Population data frame:\n\n{}".format(df_population_top),"\n\n")

Population data frame:

  cca2            name    pop2021    pop2020    pop2050    pop2030    pop2019  \
0   AF     Afghanistan  39835.428  38928.346  64682.974  48093.578  38041.754   
1   AL         Albania   2872.933   2877.797   2424.061   2786.974   2880.917   
2   DZ         Algeria  44616.624  43851.044  60923.386  50360.749  43053.054   
3   AS  American Samoa     55.100     55.191     53.581     54.728     55.312   
4   AD         Andorra     77.355     77.265     76.118     77.925     77.142   

     pop2015    pop2010    pop2000    pop1990    pop1980    pop1970     area  \
0  34413.603  29185.507  20779.953  12412.308  13356.511  11173.642   652230   
1   2890.513   2948.023   3129.243   3286.073   2682.690   2150.707    28748   
2  39728.025  35977.455  31042.235  25758.869  19221.665  14464.985  2381741   
3     55.812     56.079     57.821     47.347     32.646     27.363      199   
4     78.011     84.449     65.390     54.509     36.067     24.276      468   

    Dens

In [7]:
df_covid_vac = pd.read_csv(path.join(dir_path,"Covid_Vaccination_Data.csv"), header= 0)

df_covid_vac_top = df_covid_vac.head(5)
print("Vaccination data for each country:\n\n{}".format(df_covid_vac_top),"\n\n")

Vaccination data for each country:

  iso_code continent     location        date  total_cases  new_cases  \
0      AFG      Asia  Afghanistan  2020-02-24          5.0        5.0   
1      AFG      Asia  Afghanistan  2020-02-25          5.0        0.0   
2      AFG      Asia  Afghanistan  2020-02-26          5.0        0.0   
3      AFG      Asia  Afghanistan  2020-02-27          5.0        0.0   
4      AFG      Asia  Afghanistan  2020-02-28          5.0        0.0   

   new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  ...  \
0                 NaN           NaN         NaN                  NaN  ...   
1                 NaN           NaN         NaN                  NaN  ...   
2                 NaN           NaN         NaN                  NaN  ...   
3                 NaN           NaN         NaN                  NaN  ...   
4                 NaN           NaN         NaN                  NaN  ...   

   female_smokers  male_smokers  handwashing_facilities  \
0  

In [8]:
df_gdp = pd.read_csv(path.join(dir_path,"GDP_Actual_Value.csv"), header= 0, encoding="ISO-8859-1")

df_gdp_top = df_gdp.head(5)
print("GDP for each country:\n\n{}".format(df_gdp_top),"\n\n")

GDP for each country:

  GDP, current prices (Billions of U.S. dollars)     1980     1981     1982  \
0                                            NaN      NaN      NaN      NaN   
1                                    Afghanistan  no data  no data  no data   
2                                        Albania    1.946    2.229    2.296   
3                                        Algeria   42.346   44.372    44.78   
4                                        Andorra  no data  no data  no data   

      1983     1984     1985     1986     1987     1988  ...     2017  \
0      NaN      NaN      NaN      NaN      NaN      NaN  ...      NaN   
1  no data  no data  no data  no data  no data  no data  ...   18.883   
2    2.319     2.29    2.339    2.587    2.566     2.53  ...   13.053   
3   47.529   51.513   61.132   61.535     63.3   51.664  ...  170.207   
4  no data  no data  no data  no data  no data  no data  ...    2.993   

      2018    2019    2020     2021     2022     2023     2024 

---

## 2. Data Pre-processing

After having imported the dataset from _.csv_ files into Pandas _dataframe_, we perform pre-processing of the data before storing it in the MySQL database.

We divide the pre-processing steps into two major parts:
1. First we carry out some basic cleaning of all the datasets, which includes steps like dropping non-essential columns, checking column names and checking missing values.

2. Secondly, we normalise the country names across all the datasets by considering the country names in the `df_population` dataframe as reference.


### Part I - Basic Data Cleaning

We perform the following steps for the basic cleaning of the imported datasets:

1. Drop non-essential columns & rows and add essential columns to the dataset.
2. Remove whitespaces around the column names of the dataset. Also rename the column name if necessary.
3. Check for any missing values in the dataset and rectify them.
4. Clean the country names by removing special characters and digits.

We define the below functions to fix the column names, normalise the country names and checking of any missing values.

In [9]:
# Define a function to fix the column name of DataFrame

def fix_column_name(df):
    
    """
    This function checks and removes any whitespace
    before and after the column name. And replaces
    spaces between words with an underscore.
    
    Input:
        df: Pandas DataFrame
    
    Return:
        Pandas DataFrame
    
    """
    
    df.columns = [c.strip().replace(" ", "_") for c in df.columns]
    
    return None

In [10]:
# Define a function to check missing values in DataFrame

def find_total_missing_val_and_loc(df):
    
    """
    This function prints the total number of missing values
    in the given DataFrame for each column and returns the
    records with missing value. Otherwise, it returns "None".
    
    Input:
        df: Pandas DataFrame
    
    Return:
        Pandas DataFrame
    
    """

    missing_val = df.isnull().sum()
    
    if sum(missing_val):
        print(missing_val)
        return df.loc[df.isnull().T.any()]

    else:
        print("No missing values")
        return None

In [11]:
# Doubts
# Define a function to normalize the country name

def normalize_country_names(df, country_col):
    
    """
    Return the Unicode normal form of the strings of the
    Pandas Series with the name: country_col.
       
    Input:
        df: Pandas DataFrame
        country_col: string
    
    Returns
        df_tmp: Pandas Series
    """
    
    # Get the column which is having country name from the table
    df_tmp = df.copy() 
    country_names = df_tmp[country_col]

    # Replace `_` with whitespace
    country_names = country_names.str.replace("_", " ")

    # Remove parenthesis and any content and whitespace around it
    country_names = country_names.str.replace("\s*\(.*\)\s*", '',regex=True)
    
    # normalise the string values to remove symbols and diacritics
    norm_name = country_names.str.normalize('NFKD')
    norm_name = norm_name.str.encode('ascii',errors='ignore').str.decode('utf-8')

    df_tmp[country_col] = country_names
    
    return df_tmp

#### I. Basic cleaning of the `df_tokyo` dataframe:

In [12]:
print("Tokyo Olympics 2020 data frame:\n\n{}".format(df_tokyo_top),"\n\n")

Tokyo Olympics 2020 data frame:

      Country  Gold Medal  Silver Medal  Bronze Medal  Total  Rank By Total
0   Argentina           0             1             2      3             60
1     Armenia           0             2             2      4             47
2   Australia          17             7            22     46              6
3     Austria           1             1             5      7             33
4  Azerbaijan           0             3             4      7             33 




In the above output, `df_tokyo` contains the column **`Rank by Total`**, which we do not need in our case.

Hence, we remove this column.

In [13]:
# Drop column "Rank by Total"
df_tokyo = df_tokyo.drop(columns="Rank By Total", axis=1)

df_tokyo_top = df_tokyo.head(5)
print("Tokyo Olympics 2020 data frame:\n\n{}".format(df_tokyo_top),"\n\n")

Tokyo Olympics 2020 data frame:

      Country  Gold Medal  Silver Medal  Bronze Medal  Total
0   Argentina           0             1             2      3
1     Armenia           0             2             2      4
2   Australia          17             7            22     46
3     Austria           1             1             5      7
4  Azerbaijan           0             3             4      7 




Now, we fix the column names of the dataframe

In [14]:
# Fix column names of the dataframe
fix_column_name(df_tokyo)

df_tokyo_top = df_tokyo.head(5)
print("Tokyo Olympics 2020 data frame:\n\n{}".format(df_tokyo_top),"\n\n")

Tokyo Olympics 2020 data frame:

      Country  Gold_Medal  Silver_Medal  Bronze_Medal  Total
0   Argentina           0             1             2      3
1     Armenia           0             2             2      4
2   Australia          17             7            22     46
3     Austria           1             1             5      7
4  Azerbaijan           0             3             4      7 




Then, we check if there are any missing values

In [15]:
# Find any missing values
find_total_missing_val_and_loc(df_tokyo)

No missing values


Finally, we normalise the country names

In [16]:
# Clean the country names
df_tokyo = normalize_country_names(df_tokyo, "Country")

In [17]:
df_tokyo_top = df_tokyo.head(5)
print("Tokyo Olympics 2020 data frame:\n\n{}".format(df_tokyo_top),"\n\n")

Tokyo Olympics 2020 data frame:

      Country  Gold_Medal  Silver_Medal  Bronze_Medal  Total
0   Argentina           0             1             2      3
1     Armenia           0             2             2      4
2   Australia          17             7            22     46
3     Austria           1             1             5      7
4  Azerbaijan           0             3             4      7 




#### II. Basic cleaning of the `df_rio` dataframe:

In [18]:
print("Rio Olympics 2016 data frame:\n\n{}".format(df_rio_top),"\n\n")

Rio Olympics 2016 data frame:

     Country  Gold  Silver  Bronze
0    Algeria     0       2       0
1  Argentina     3       1       0
2    Armenia     1       3       0
3  Australia     8      11      10
4    Austria     0       0       1 




In the above output, `df_rio`, do not contain the column **`Total`**.

Hence we are add this column.

In [19]:
# Add column "Total"
df_rio["Total"] = df_rio.iloc[:,1:3].sum(axis=1)

df_rio_top = df_rio.head(5)
print("Rio Olympics 2016 data frame:\n\n{}".format(df_rio_top),"\n\n")

Rio Olympics 2016 data frame:

     Country  Gold  Silver  Bronze  Total
0    Algeria     0       2       0      2
1  Argentina     3       1       0      4
2    Armenia     1       3       0      4
3  Australia     8      11      10     19
4    Austria     0       0       1      0 




Now, we fix the column names of the dataframe

In [20]:
# Fix column names of the dataframe
fix_column_name(df_rio)

df_rio_top = df_rio.head(5)
print("Rio Olympics 2016 data frame:\n\n{}".format(df_rio_top),"\n\n")

Rio Olympics 2016 data frame:

     Country  Gold  Silver  Bronze  Total
0    Algeria     0       2       0      2
1  Argentina     3       1       0      4
2    Armenia     1       3       0      4
3  Australia     8      11      10     19
4    Austria     0       0       1      0 




Then, we check if there are any missing values

In [21]:
# Find any missing values
find_total_missing_val_and_loc(df_rio)

No missing values


Finally, we normalise the country names

In [22]:
# Clean the country names
df_rio = normalize_country_names(df_rio, "Country")

In [23]:
df_rio_top = df_rio.head(5)
print("Rio Olympics 2016 data frame:\n\n{}".format(df_rio_top),"\n\n")

Rio Olympics 2016 data frame:

     Country  Gold  Silver  Bronze  Total
0    Algeria     0       2       0      2
1  Argentina     3       1       0      4
2    Armenia     1       3       0      4
3  Australia     8      11      10     19
4    Austria     0       0       1      0 




#### III. Basic cleaning of the `df_london` dataframe:

In [24]:
print("London Olympics 2012 data frame:\n\n{}".format(df_london_top),"\n\n")

London Olympics 2012 data frame:

       Country  Gold Medal  Silver Medal  Bronze Medal  Total
0  Afghanistan           0             0             1      1
1      Algeria           1             0             0      1
2    Argentina           1             1             2      4
3      Armenia           0             1             1      2
4    Australia           8            15            12     35 




There is no need to add or remove any column here.

Now, we fix the column names

In [25]:
# Fix column names of the dataframe
fix_column_name(df_london)

df_london_top = df_london.head(5)
print("London Olympics 2012 data frame:\n\n{}".format(df_london_top),"\n\n")

London Olympics 2012 data frame:

       Country  Gold_Medal  Silver_Medal  Bronze_Medal  Total
0  Afghanistan           0             0             1      1
1      Algeria           1             0             0      1
2    Argentina           1             1             2      4
3      Armenia           0             1             1      2
4    Australia           8            15            12     35 




Then, we check if there are any missing values

In [26]:
# Find any missing values
find_total_missing_val_and_loc(df_london)

No missing values


Finally, we normalise the country names

In [27]:
# Clean the country names
df_london = normalize_country_names(df_london, "Country")

In [28]:
df_london_top = df_london.head(5)
print("London Olympics 2012 data frame:\n\n{}".format(df_london_top),"\n\n")

London Olympics 2012 data frame:

       Country  Gold_Medal  Silver_Medal  Bronze_Medal  Total
0  Afghanistan           0             0             1      1
1      Algeria           1             0             0      1
2    Argentina           1             1             2      4
3      Armenia           0             1             1      2
4    Australia           8            15            12     35 




#### IV. Basic cleaning of the `df_population` dataframe:

In [29]:
print("Population data frame:\n\n{}".format(df_population_top),"\n\n")

Population data frame:

  cca2            name    pop2021    pop2020    pop2050    pop2030    pop2019  \
0   AF     Afghanistan  39835.428  38928.346  64682.974  48093.578  38041.754   
1   AL         Albania   2872.933   2877.797   2424.061   2786.974   2880.917   
2   DZ         Algeria  44616.624  43851.044  60923.386  50360.749  43053.054   
3   AS  American Samoa     55.100     55.191     53.581     54.728     55.312   
4   AD         Andorra     77.355     77.265     76.118     77.925     77.142   

     pop2015    pop2010    pop2000    pop1990    pop1980    pop1970     area  \
0  34413.603  29185.507  20779.953  12412.308  13356.511  11173.642   652230   
1   2890.513   2948.023   3129.243   3286.073   2682.690   2150.707    28748   
2  39728.025  35977.455  31042.235  25758.869  19221.665  14464.985  2381741   
3     55.812     56.079     57.821     47.347     32.646     27.363      199   
4     78.011     84.449     65.390     54.509     36.067     24.276      468   

    Dens

We only nead Country Name, and Population for 2020, and 2021.

Hence we drop the other columns.

In [30]:
df_population = df_population[["name","pop2021","pop2020"]]

df_population_top = df_population.head(5)
print("Population data frame:\n\n{}".format(df_population_top),"\n\n")

Population data frame:

             name    pop2021    pop2020
0     Afghanistan  39835.428  38928.346
1         Albania   2872.933   2877.797
2         Algeria  44616.624  43851.044
3  American Samoa     55.100     55.191
4         Andorra     77.355     77.265 




Now, we fix the column names of the dataframe

In [31]:
# Fix column names of the dataframe
fix_column_name(df_population)

df_population_top = df_population.head(5)
print("Population data frame:\n\n{}".format(df_population_top),"\n\n")

Population data frame:

             name    pop2021    pop2020
0     Afghanistan  39835.428  38928.346
1         Albania   2872.933   2877.797
2         Algeria  44616.624  43851.044
3  American Samoa     55.100     55.191
4         Andorra     77.355     77.265 




Then, we check if there are any missing values

In [32]:
# Find any missing values
find_total_missing_val_and_loc(df_population)

No missing values


Finally, we normalise the country names

In [33]:
# Clean the country names
df_population = normalize_country_names(df_population, "name")

In [34]:
df_population_top = df_population.head(5)
print("Population data frame:\n\n{}".format(df_population_top),"\n\n")

Population data frame:

             name    pop2021    pop2020
0     Afghanistan  39835.428  38928.346
1         Albania   2872.933   2877.797
2         Algeria  44616.624  43851.044
3  American Samoa     55.100     55.191
4         Andorra     77.355     77.265 




We observe that population values are divided by 1000 in the _.csv_ file.

So, we multiply the values of both the population columns by 1000 to get the correct population numbers.

In [35]:
df_population['pop2021'] = df_population['pop2021'].apply(lambda x : x * 1000)
df_population['pop2020'] = df_population['pop2020'].apply(lambda x : x * 1000)

In [36]:
df_population_top = df_population.head(5)
print("Population data frame:\n\n{}".format(df_population_top),"\n\n")

Population data frame:

             name     pop2021     pop2020
0     Afghanistan  39835428.0  38928346.0
1         Albania   2872933.0   2877797.0
2         Algeria  44616624.0  43851044.0
3  American Samoa     55100.0     55191.0
4         Andorra     77355.0     77265.0 




#### V. Basic cleaning of the `df_covid_vac` dataframe:

In [37]:
print("Vaccination data for each country:\n\n{}".format(df_covid_vac_top),"\n\n")

Vaccination data for each country:

  iso_code continent     location        date  total_cases  new_cases  \
0      AFG      Asia  Afghanistan  2020-02-24          5.0        5.0   
1      AFG      Asia  Afghanistan  2020-02-25          5.0        0.0   
2      AFG      Asia  Afghanistan  2020-02-26          5.0        0.0   
3      AFG      Asia  Afghanistan  2020-02-27          5.0        0.0   
4      AFG      Asia  Afghanistan  2020-02-28          5.0        0.0   

   new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  ...  \
0                 NaN           NaN         NaN                  NaN  ...   
1                 NaN           NaN         NaN                  NaN  ...   
2                 NaN           NaN         NaN                  NaN  ...   
3                 NaN           NaN         NaN                  NaN  ...   
4                 NaN           NaN         NaN                  NaN  ...   

   female_smokers  male_smokers  handwashing_facilities  \
0  

This dataframe has many columns. So lets see what are the column names in the table and keep only required columns

In [38]:
for i, c in enumerate(df_covid_vac.columns):
    print(i, c)

0 iso_code
1 continent
2 location
3 date
4 total_cases
5 new_cases
6 new_cases_smoothed
7 total_deaths
8 new_deaths
9 new_deaths_smoothed
10 total_cases_per_million
11 new_cases_per_million
12 new_cases_smoothed_per_million
13 total_deaths_per_million
14 new_deaths_per_million
15 new_deaths_smoothed_per_million
16 reproduction_rate
17 icu_patients
18 icu_patients_per_million
19 hosp_patients
20 hosp_patients_per_million
21 weekly_icu_admissions
22 weekly_icu_admissions_per_million
23 weekly_hosp_admissions
24 weekly_hosp_admissions_per_million
25 new_tests
26 total_tests
27 total_tests_per_thousand
28 new_tests_per_thousand
29 new_tests_smoothed
30 new_tests_smoothed_per_thousand
31 positive_rate
32 tests_per_case
33 tests_units
34 total_vaccinations
35 people_vaccinated
36 people_fully_vaccinated
37 total_boosters
38 new_vaccinations
39 new_vaccinations_smoothed
40 total_vaccinations_per_hundred
41 people_vaccinated_per_hundred
42 people_fully_vaccinated_per_hundred
43 total_boosters_

We only need following columns:
* 2 location  >>(country name)
* 3 date
* 4 total_cases
* 5 new_cases
* 7 total_deaths
* 8 new_deaths
* 34 total_vaccinations
* 35 people_vaccinated
* 36 people_fully_vaccinated

In [39]:
df_covid_vac = df_covid_vac[["location", "date", "total_cases", "new_cases", "total_deaths", "new_deaths", 
                      "people_vaccinated", "people_fully_vaccinated"]]
df_covid_vac

location        date  total_cases  new_cases  total_deaths  \
0       Afghanistan  2020-02-24          5.0        5.0           NaN   
1       Afghanistan  2020-02-25          5.0        0.0           NaN   
2       Afghanistan  2020-02-26          5.0        0.0           NaN   
3       Afghanistan  2020-02-27          5.0        0.0           NaN   
4       Afghanistan  2020-02-28          5.0        0.0           NaN   
...             ...         ...          ...        ...           ...   
134875     Zimbabwe  2021-11-17     133557.0       52.0        4699.0   
134876     Zimbabwe  2021-11-18     133593.0       36.0        4699.0   
134877     Zimbabwe  2021-11-19     133593.0        0.0        4699.0   
134878     Zimbabwe  2021-11-20     133615.0       22.0        4699.0   
134879     Zimbabwe  2021-11-21     133647.0       32.0        4699.0   

        new_deaths  people_vaccinated  people_fully_vaccinated  
0              NaN                NaN                      NaN  
1              NaN                NaN                      NaN  
2              NaN                NaN                      NaN  
3              NaN                NaN                      NaN  
4              NaN                NaN                      NaN  
...            ...                ...                      ...  
134875         1.0                NaN                      NaN  
134876         0.0          3583256.0                2727175.0  
134877         0.0          3625221.0                2737278.0  
134878         0.0          3651820.0                2744192.0  
134879         0.0          3672011.0                2747693.0  

[134880 rows x 8 columns]

In [40]:
df_unique_country_name = pd.DataFrame(df_covid_vac.location.unique(), columns=["Country_Name"])

df_unique_country_name

Country_Name
0                         Afghanistan
1                              Africa
2                             Albania
3                             Algeria
4                             Andorra
5                              Angola
6                            Anguilla
7                 Antigua and Barbuda
8                           Argentina
9                             Armenia
10                              Aruba
11                               Asia
12                          Australia
13                            Austria
14                         Azerbaijan
15                            Bahamas
16                            Bahrain
17                         Bangladesh
18                           Barbados
19                            Belarus
20                            Belgium
21                             Belize
22                              Benin
23                            Bermuda
24                             Bhutan
25                            Bolivia
26    Bonaire Sint Eustatius and Saba
27             Bosnia and Herzegovina
28                           Botswana
29                             Brazil
30             British Virgin Islands
31                             Brunei
32                           Bulgaria
33                       Burkina Faso
34                            Burundi
35                           Cambodia
36                           Cameroon
37                             Canada
38                         Cape Verde
39                     Cayman Islands
40           Central African Republic
41                               Chad
42                              Chile
43                              China
44                           Colombia
45                            Comoros
46                              Congo
47                       Cook Islands
48                         Costa Rica
49                      Cote d'Ivoire
50                            Croatia
51                               Cuba
52                            Curacao
53                             Cyprus
54                            Czechia
55       Democratic Republic of Congo
56                            Denmark
57                           Djibouti
58                           Dominica
59                 Dominican Republic
60                            Ecuador
61                              Egypt
62                        El Salvador
63                  Equatorial Guinea
64                            Eritrea
65                            Estonia
66                           Eswatini
67                           Ethiopia
68                             Europe
69                     European Union
70                     Faeroe Islands
71                   Falkland Islands
72                               Fiji
73                            Finland
74                             France
75                   French Polynesia
76                              Gabon
77                             Gambia
78                            Georgia
79                            Germany
80                              Ghana
81                          Gibraltar
82                             Greece
83                          Greenland
84                            Grenada
85                          Guatemala
86                           Guernsey
87                             Guinea
88                      Guinea-Bissau
89                             Guyana
90                              Haiti
91                        High income
92                           Honduras
93                          Hong Kong
94                            Hungary
95                            Iceland
96                              India
97                          Indonesia
98                      International
99                               Iran
100                              Iraq
101                           Ireland
102                       Isle of Man
103                            Israel
104                             Ita

From the above, we can see that the dataset also contains the below entries which are not names of a country.

* Africa
* Asia
* Europe
* European Union
* High income
* International
* Low income
* Lower middle income
* North America
* Oceania
* South America
* Upper middle income
* World

In [41]:
to_remove = ["Africa", "Asia", "Europe", "European Union", "High income", 
             "International", "Low income", "Lower middle income", 
             "North America", "Oceania","South America", "Upper middle income","World"]

for name in to_remove:
    df_covid_vac.drop(df_covid_vac[df_covid_vac['location'] == name].index, inplace = True)

df_unique_country_name = pd.DataFrame(df_covid_vac.location.unique(), columns=["Country_Name"])

df_unique_country_name

Country_Name
0                         Afghanistan
1                             Albania
2                             Algeria
3                             Andorra
4                              Angola
5                            Anguilla
6                 Antigua and Barbuda
7                           Argentina
8                             Armenia
9                               Aruba
10                          Australia
11                            Austria
12                         Azerbaijan
13                            Bahamas
14                            Bahrain
15                         Bangladesh
16                           Barbados
17                            Belarus
18                            Belgium
19                             Belize
20                              Benin
21                            Bermuda
22                             Bhutan
23                            Bolivia
24    Bonaire Sint Eustatius and Saba
25             Bosnia and Herzegovina
26                           Botswana
27                             Brazil
28             British Virgin Islands
29                             Brunei
30                           Bulgaria
31                       Burkina Faso
32                            Burundi
33                           Cambodia
34                           Cameroon
35                             Canada
36                         Cape Verde
37                     Cayman Islands
38           Central African Republic
39                               Chad
40                              Chile
41                              China
42                           Colombia
43                            Comoros
44                              Congo
45                       Cook Islands
46                         Costa Rica
47                      Cote d'Ivoire
48                            Croatia
49                               Cuba
50                            Curacao
51                             Cyprus
52                            Czechia
53       Democratic Republic of Congo
54                            Denmark
55                           Djibouti
56                           Dominica
57                 Dominican Republic
58                            Ecuador
59                              Egypt
60                        El Salvador
61                  Equatorial Guinea
62                            Eritrea
63                            Estonia
64                           Eswatini
65                           Ethiopia
66                     Faeroe Islands
67                   Falkland Islands
68                               Fiji
69                            Finland
70                             France
71                   French Polynesia
72                              Gabon
73                             Gambia
74                            Georgia
75                            Germany
76                              Ghana
77                          Gibraltar
78                             Greece
79                          Greenland
80                            Grenada
81                          Guatemala
82                           Guernsey
83                             Guinea
84                      Guinea-Bissau
85                             Guyana
86                              Haiti
87                           Honduras
88                          Hong Kong
89                            Hungary
90                            Iceland
91                              India
92                          Indonesia
93                               Iran
94                               Iraq
95                            Ireland
96                        Isle of Man
97                             Israel
98                              Italy
99                            Jamaica
100                             Japan
101                            Jersey
102                            Jordan
103                        Kazakhstan
104                             Ken

Now, we fix the column names of the dataframe

In [42]:
# Fix column names of the dataframe
fix_column_name(df_covid_vac)

df_covid_vac_top = df_covid_vac.head(5)
print("Vaccination data for each country:\n\n{}".format(df_covid_vac_top),"\n\n")

Vaccination data for each country:

      location        date  total_cases  new_cases  total_deaths  new_deaths  \
0  Afghanistan  2020-02-24          5.0        5.0           NaN         NaN   
1  Afghanistan  2020-02-25          5.0        0.0           NaN         NaN   
2  Afghanistan  2020-02-26          5.0        0.0           NaN         NaN   
3  Afghanistan  2020-02-27          5.0        0.0           NaN         NaN   
4  Afghanistan  2020-02-28          5.0        0.0           NaN         NaN   

   people_vaccinated  people_fully_vaccinated  
0                NaN                      NaN  
1                NaN                      NaN  
2                NaN                      NaN  
3                NaN                      NaN  
4                NaN                      NaN   




Then, we check if there are any missing values

In [43]:
# Find any missing values
find_total_missing_val_and_loc(df_covid_vac)

location                        0
date                            0
total_cases                  7393
new_cases                    7402
total_deaths                18384
new_deaths                  18388
people_vaccinated           97323
people_fully_vaccinated    100128
dtype: int64


location        date  total_cases  new_cases  total_deaths  \
0       Afghanistan  2020-02-24          5.0        5.0           NaN   
1       Afghanistan  2020-02-25          5.0        0.0           NaN   
2       Afghanistan  2020-02-26          5.0        0.0           NaN   
3       Afghanistan  2020-02-27          5.0        0.0           NaN   
4       Afghanistan  2020-02-28          5.0        0.0           NaN   
...             ...         ...          ...        ...           ...   
134792     Zimbabwe  2021-08-26     123986.0      275.0        4356.0   
134803     Zimbabwe  2021-09-06     125671.0      121.0        4493.0   
134809     Zimbabwe  2021-09-12     126269.0       49.0        4538.0   
134814     Zimbabwe  2021-09-17     127632.0      264.0        4562.0   
134875     Zimbabwe  2021-11-17     133557.0       52.0        4699.0   

        new_deaths  people_vaccinated  people_fully_vaccinated  
0              NaN                NaN                      NaN  
1              NaN                NaN                      NaN  
2              NaN                NaN                      NaN  
3              NaN                NaN                      NaN  
4              NaN                NaN                      NaN  
...            ...                ...                      ...  
134792        18.0                NaN                      NaN  
134803        11.0                NaN                      NaN  
134809         2.0                NaN                      NaN  
134814         2.0                NaN                      NaN  
134875         1.0                NaN                      NaN  

[102126 rows x 8 columns]

For the `df_covid_vac` dataframe, we replace the `NaN` with the `0`

In [44]:
df_covid_vac.fillna(value=0, inplace=True)

In [45]:
# Check if any missing values still left
find_total_missing_val_and_loc(df_covid_vac)

No missing values


Finally, we normalise the country names

In [46]:
# Clean the country names
df_covid_vac = normalize_country_names(df_covid_vac, "location")

In [47]:
df_covid_vac_top = df_covid_vac.head(5)
print("Vaccination data for each country:\n\n{}".format(df_covid_vac_top),"\n\n")

Vaccination data for each country:

      location        date  total_cases  new_cases  total_deaths  new_deaths  \
0  Afghanistan  2020-02-24          5.0        5.0           0.0         0.0   
1  Afghanistan  2020-02-25          5.0        0.0           0.0         0.0   
2  Afghanistan  2020-02-26          5.0        0.0           0.0         0.0   
3  Afghanistan  2020-02-27          5.0        0.0           0.0         0.0   
4  Afghanistan  2020-02-28          5.0        0.0           0.0         0.0   

   people_vaccinated  people_fully_vaccinated  
0                0.0                      0.0  
1                0.0                      0.0  
2                0.0                      0.0  
3                0.0                      0.0  
4                0.0                      0.0   




#### VI. Basic cleaning of the `df_gdp` dataframe:

In [48]:
print("GDP for each country:\n\n{}".format(df_gdp_top),"\n\n")

GDP for each country:

  GDP, current prices (Billions of U.S. dollars)     1980     1981     1982  \
0                                            NaN      NaN      NaN      NaN   
1                                    Afghanistan  no data  no data  no data   
2                                        Albania    1.946    2.229    2.296   
3                                        Algeria   42.346   44.372    44.78   
4                                        Andorra  no data  no data  no data   

      1983     1984     1985     1986     1987     1988  ...     2017  \
0      NaN      NaN      NaN      NaN      NaN      NaN  ...      NaN   
1  no data  no data  no data  no data  no data  no data  ...   18.883   
2    2.319     2.29    2.339    2.587    2.566     2.53  ...   13.053   
3   47.529   51.513   61.132   61.535     63.3   51.664  ...  170.207   
4  no data  no data  no data  no data  no data  no data  ...    2.993   

      2018    2019    2020     2021     2022     2023     2024 

This dataframe has many columns. So lets see what are the column names in the table and keep only required columns

In [49]:
for i, c in enumerate(df_gdp.columns):
    print(i, c)

0 GDP, current prices (Billions of U.S. dollars)
1 1980
2 1981
3 1982
4 1983
5 1984
6 1985
7 1986
8 1987
9 1988
10 1989
11 1990
12 1991
13 1992
14 1993
15 1994
16 1995
17 1996
18 1997
19 1998
20 1999
21 2000
22 2001
23 2002
24 2003
25 2004
26 2005
27 2006
28 2007
29 2008
30 2009
31 2010
32 2011
33 2012
34 2013
35 2014
36 2015
37 2016
38 2017
39 2018
40 2019
41 2020
42 2021
43 2022
44 2023
45 2024
46 2025
47 2026


Rename the column: "GDP, current prices (Billions of U.S. dollars)".

In [50]:
df_gdp.rename(columns={"GDP, current prices (Billions of U.S. dollars)": "Country"}, inplace=True)

df_gdp.head(5)

Country     1980     1981     1982     1983     1984     1985     1986  \
0          NaN      NaN      NaN      NaN      NaN      NaN      NaN      NaN   
1  Afghanistan  no data  no data  no data  no data  no data  no data  no data   
2      Albania    1.946    2.229    2.296    2.319     2.29    2.339    2.587   
3      Algeria   42.346   44.372    44.78   47.529   51.513   61.132   61.535   
4      Andorra  no data  no data  no data  no data  no data  no data  no data   

      1987     1988  ...     2017     2018    2019    2020     2021     2022  \
0      NaN      NaN  ...      NaN      NaN     NaN     NaN      NaN      NaN   
1  no data  no data  ...   18.883   18.401  18.876  20.136  no data  no data   
2    2.566     2.53  ...   13.053   15.147  15.283  14.828    16.77   18.012   
3     63.3   51.664  ...  170.207  175.367  171.07   147.6  163.812  168.195   
4  no data  no data  ...    2.993    3.217   3.155   2.858    3.213     3.46   

      2023     2024     2025     2026  
0      NaN      NaN      NaN      NaN  
1  no data  no data  no data  no data  
2   18.931   20.026    21.15   22.308  
3  172.094  173.719  174.376  175.228  
4    3.659    3.851    4.017    4.179  

[5 rows x 48 columns]

We only need following columns:
* 0 Country
* 33 2012
* 34 2013
* 35 2014
* 36 2015
* 37 2016
* 38 2017
* 39 2018
* 40 2019
* 41 2020
* 42 2021

In [51]:
df_gdp = df_gdp[["Country","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021"]]
df_gdp

Country       2012       2013  \
0                                         NaN        NaN        NaN   
1                                 Afghanistan     20.293      20.17   
2                                     Albania     12.324     12.784   
3                                     Algeria    209.059    209.755   
4                                     Andorra      3.189      3.193   
5                                      Angola    128.053     136.71   
6                         Antigua and Barbuda        1.2      1.181   
7                                   Argentina    579.666    611.471   
8                                     Armenia     10.619     11.121   
9                                       Aruba      2.615      2.728   
10                                  Australia   1569.311   1518.426   
11                                    Austria    409.661    430.197   
12                                 Azerbaijan     69.687      74.16   
13                               Bahamas, The      10.72     10.495   
14                                    Bahrain     30.749     32.539   
15                                 Bangladesh    133.304    150.026   
16                                   Barbados       4.61      4.677   
17                                    Belarus     65.669     75.496   
18                                    Belgium    496.467    521.799   
19                                     Belize      1.523      1.579   
20                                      Benin     11.148     12.518   
21                                     Bhutan      1.772      1.805   
22                                    Bolivia     27.282     30.883   
23                     Bosnia and Herzegovina     17.207     18.155   
24                                   Botswana     15.519     14.368   
25                                     Brazil   2464.054   2471.718   
26                          Brunei Darussalam     19.047     18.092   
27                                   Bulgaria     54.031     55.617   
28                               Burkina Faso     12.569     13.444   
29                                    Burundi      2.333      2.456   
30                                 Cabo Verde      1.742       1.85   
31                                   Cambodia     14.057     15.228   
32                                   Cameroon     29.121     32.358   
33                                     Canada   1828.362   1846.595   
34                   Central African Republic      2.512      1.692   
35                                       Chad     12.411     12.994   
36                                      Chile    267.021    278.347   
37                China, People's Republic of   8539.584   9624.928   
38                                   Colombia    370.691    382.093   
39                                    Comoros      1.016      1.116   
40                    Congo, Dem. Rep. of the      29.35     32.695   
41                        Congo, Republic of      17.704     17.959   
42                                 Costa Rica     47.231     50.949   
43                                    Croatia     56.581     58.194   
44                                     Cyprus     24.993       23.9   
45                             Czech Republic    208.858    211.686   
46                              Cte d'Ivoire      37.03     43.228   
47                                    Denmark    327.149    343.584   
48                                   Djibouti        1.9      2.043   
49                                   Dominica      0.486      0.498   
50                         Dominican Republic     60.747     62.758   
51                                    Ecuador     87.925      95.13   
52                                      Egypt    278.769    288.007   
53                                El Salvador     21.386     21.991   
54                          Equatorial Guinea     22.388     21.949   
55                                    Eritrea      2.255      

Now, we fix the column names of the dataframe

In [52]:
# Fix column names of the dataframe
fix_column_name(df_gdp)

df_gdp_top = df_gdp.head(5)
print("GDP for each country:\n\n{}".format(df_gdp_top),"\n\n")

GDP for each country:

       Country     2012     2013    2014     2015     2016     2017     2018  \
0          NaN      NaN      NaN     NaN      NaN      NaN      NaN      NaN   
1  Afghanistan   20.293    20.17  20.616   20.057    18.02   18.883   18.401   
2      Albania   12.324   12.784  13.246   11.389   11.862   13.053   15.147   
3      Algeria  209.059  209.755  213.81  165.979  160.034  170.207  175.367   
4      Andorra    3.189    3.193   3.267    2.789    2.895    2.993    3.217   

     2019    2020     2021  
0     NaN     NaN      NaN  
1  18.876  20.136  no data  
2  15.283  14.828    16.77  
3  171.07   147.6  163.812  
4   3.155   2.858    3.213   




Then, we check if there are any missing values

In [53]:
find_total_missing_val_and_loc(df_gdp)

Country    2
2012       3
2013       3
2014       3
2015       3
2016       3
2017       3
2018       3
2019       3
2020       3
2021       3
dtype: int64


Country 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021
0           NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
229         NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
230  ©IMF, 2021  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

We remove rows with indices 0, 229 and 230 as they junk rows with no country name and gdp value.

In [54]:
df_gdp.drop([0,229,230], axis=0, inplace=True)

We also remove the rows with indices in the range[197, 228] as these rows do not correspond to any country but rather to various regions of the world.

In [55]:
df_gdp.drop(df_gdp.index[197:228], axis=0, inplace=True)

We also observe that some records are marked as _'no data'_.

We replace these records with 0

In [56]:
df_gdp.replace(['no data'], [0], inplace=True)

In [57]:
df_gdp_top = df_gdp.head(5)
print("GDP for each country:\n\n{}".format(df_gdp_top),"\n\n")

GDP for each country:

       Country     2012     2013     2014     2015     2016     2017     2018  \
1  Afghanistan   20.293    20.17   20.616   20.057    18.02   18.883   18.401   
2      Albania   12.324   12.784   13.246   11.389   11.862   13.053   15.147   
3      Algeria  209.059  209.755   213.81  165.979  160.034  170.207  175.367   
4      Andorra    3.189    3.193    3.267    2.789    2.895    2.993    3.217   
5       Angola  128.053   136.71  145.712  116.194  101.124  122.022  101.353   

     2019    2020     2021  
1  18.876  20.136        0  
2  15.283  14.828    16.77  
3  171.07   147.6  163.812  
4   3.155   2.858    3.213  
5  84.516  58.376   70.339   




In [58]:
find_total_missing_val_and_loc(df_gdp)

No missing values


Finally, we normalise the country names

In [59]:
# Clean the country names
df_gdp = normalize_country_names(df_gdp, "Country")

In [60]:
df_gdp_top = df_gdp.head(5)
print("GDP for each country:\n\n{}".format(df_gdp_top),"\n\n")

GDP for each country:

       Country     2012     2013     2014     2015     2016     2017     2018  \
1  Afghanistan   20.293    20.17   20.616   20.057    18.02   18.883   18.401   
2      Albania   12.324   12.784   13.246   11.389   11.862   13.053   15.147   
3      Algeria  209.059  209.755   213.81  165.979  160.034  170.207  175.367   
4      Andorra    3.189    3.193    3.267    2.789    2.895    2.993    3.217   
5       Angola  128.053   136.71  145.712  116.194  101.124  122.022  101.353   

     2019    2020     2021  
1  18.876  20.136        0  
2  15.283  14.828    16.77  
3  171.07   147.6  163.812  
4   3.155   2.858    3.213  
5  84.516  58.376   70.339   




---

### Part II - Matching country names of all dataframes to that of the `df_population` dataframe

Now we proceed to the second part of the data pre-processing section, where we match and normalise the country name of all the dataframes with reference to the country names in the `df_population` dataframe.

We define the below functions to match and normalise the country names.

In [61]:
# Define function to first save each DF's index and work with the unmatching records only.

def filter_unmatched_index(df_primary, df_ancillary, col_primary, col_ancillary):
    """
    This function returns the non-matching entries on columns
    given with indexes in columns 'primary' and 'ancillary'
    
    This function also saves each DF's index as 'index_primary'
    and 'index_ancillary', and return the records which are not
    matching between the two columns.
    """
    df_p = df_primary[[col_primary]]
    df_p.index.name = 'index_primary'
    df_p.reset_index(inplace=True)
    
    df_a = df_ancillary[[col_ancillary]]
    df_a.index.name = 'index_ancillary'
    df_a.reset_index(inplace=True)
    
    df_outer = pd.merge(df_p, df_a, left_on=col_primary, right_on=col_ancillary, how="outer")
    index_nulls = find_total_missing_val_and_loc(df_outer)
    
    return index_nulls

In [62]:
# Define the function to check for similarities between country names with 'difflib'.

def get_close_matches(name, list_compare, pad=True):
    
    """
    This function returns the best matching entry
    from 'list_compare' to 'name'
    
    Input:
        name: string
        list_compare: [string]
        
    """
    from difflib import get_close_matches
    match_list = get_close_matches(name, list_compare, n=1, cutoff=0.5)
    
    if len(match_list):
        return match_list[0]
    else:
        return name if pad else None 

In [63]:
# Define a function to add columns: best-matched and no-match for country names

def find_divergence(df, col_name):
    """
    This function adds "CnT-pad" and "CnT-noPad" and
    returns the records with non-matching country names
    of df with df_population.
    
    Input:
        df: Pandas DataFrame
        col_name: string
    
    Return:
        Pandas DataFrame

    """
    df_2 = df.copy()

    # merge tables
    df_merge_unmatch = filter_unmatched_index(df_population, df_2,"name", col_name)

    # Define the country name in "df_2" as the primary series
    # Then modify with the values from "Population-2020-21" table
    primary = df_merge_unmatch[col_name].dropna()
    options = df_merge_unmatch["name"].dropna()

    # Add column 'CnT-pad' to "df_merge_unmatch" with either the best match from options (if any)
    # or the primary/self (if there is no good match)
    df_merge_unmatch["CnT-pad"] = primary.apply(lambda country: get_close_matches(country, options))

    # Add column 'CnT-noPad' to "df_merge_unmatch" which has None when there is no good match
    df_merge_unmatch["CnT-noPad"] = primary.apply(lambda country: get_close_matches(country, options, pad=False))

    return df_merge_unmatch[["index_primary", "name", "index_ancillary", col_name,"CnT-pad","CnT-noPad"]]


#### I. Match country names in `df_tokyo`:

In [64]:
df_tmp = find_divergence(df_tokyo, df_tokyo.columns[0])

df_tmp

index_primary       12
name                12
index_ancillary    151
Country            151
dtype: int64


index_primary                              name  index_ancillary  \
0              0.0                       Afghanistan              NaN   
1              1.0                           Albania              NaN   
2              2.0                           Algeria              NaN   
3              3.0                    American Samoa              NaN   
4              4.0                           Andorra              NaN   
5              5.0                            Angola              NaN   
6              6.0                          Anguilla              NaN   
7              7.0               Antigua and Barbuda              NaN   
10            10.0                             Aruba              NaN   
16            16.0                        Bangladesh              NaN   
17            17.0                          Barbados              NaN   
20            20.0                            Belize              NaN   
21            21.0                             Benin              NaN   
23            23.0                            Bhutan              NaN   
24            24.0                           Bolivia              NaN   
25            25.0            Bosnia and Herzegovina              NaN   
28            28.0            British Virgin Islands              NaN   
29            29.0                            Brunei              NaN   
32            32.0                           Burundi              NaN   
33            33.0                          Cambodia              NaN   
34            34.0                          Cameroon              NaN   
36            36.0                        Cape Verde              NaN   
37            37.0                    Cayman Islands              NaN   
38            38.0          Central African Republic              NaN   
39            39.0                              Chad              NaN   
40            40.0                             Chile              NaN   
41            41.0                             China              NaN   
43            43.0                           Comoros              NaN   
44            44.0                      Cook Islands              NaN   
45            45.0                        Costa Rica              NaN   
48            48.0                           Curacao              NaN   
49            49.0                            Cyprus              NaN   
52            52.0                          Djibouti              NaN   
53            53.0                          Dominica              NaN   
55            55.0                          DR Congo              NaN   
58            58.0                       El Salvador              NaN   
59            59.0                 Equatorial Guinea              NaN   
60            60.0                           Eritrea              NaN   
62            62.0                          Eswatini              NaN   
64            64.0                  Falkland Islands              NaN   
65            65.0                     Faroe Islands              NaN   
69            69.0                     French Guiana              NaN   
70            70.0                  French Polynesia              NaN   
71            71.0                             Gabon              NaN   
72            72.0                            Gambia              NaN   
76            76.0                         Gibraltar              NaN   
78            78.0                         Greenland              NaN   
80            80.0                        Guadeloupe              NaN   
81            81.0                              Guam              NaN   
82            82.0                         Guatemala              NaN   
83            83.0                            Guinea              NaN   
84            84.0                     Guinea-Bissau              NaN   
85            85.0                            Guyana              NaN   
86            86.0                             Haiti           

We can see that some associations have been correctly identified

* Hong Kong, China -> Hong Kong
* United States of America -> United States	

And some associations could not found correctly:
* Great Britain	-> 	United Kingdom
* Islamic Republic of Iran -> Iran
* People's Republic of China -> China
* Republic of Korea	-> South Korea
* Republic of Moldova -> Moldova
* ROC -> Russia
* Syrian Arab Republic -> Syria
* Chinese Taipei -> Taiwan
* Cote d'Ivoire	-> Ivory Coast

So, first we apply the 'CnT-pad' associations and then correct the wrong values manually

In [65]:
# First copy the 'CnT-pad' column and then fix wrong values manually
df_tmp["pop_fixed"] = df_tmp["CnT-pad"].copy()

df_tmp.loc[232, 'pop_fixed'] = "Ivory Coast"
df_tmp.loc[234, 'pop_fixed'] = "United Kingdom"
df_tmp.loc[236, 'pop_fixed'] = "Iran"
df_tmp.loc[238, 'pop_fixed'] = "China"
df_tmp.loc[239, 'pop_fixed'] = "South Korea"
df_tmp.loc[240, 'pop_fixed'] = "Moldova"
df_tmp.loc[241, 'pop_fixed'] = "Russia"
df_tmp.loc[242, 'pop_fixed'] = "Syria"
df_tmp.loc[233, 'pop_fixed'] = "Taiwan"

# Now put the obtained values back into the df_2 data frame with the correct indexes
index_tmp = df_tmp['index_ancillary'].dropna().astype(int)
names_tmp = df_tmp['pop_fixed'].dropna().values
df_tokyo.loc[index_tmp, df_tokyo.columns[0]] = names_tmp

df_tmp = filter_unmatched_index(df_population, df_tokyo,"name", df_tokyo.columns[0])
df_tmp

index_primary        1
name                 1
index_ancillary    140
Country            140
dtype: int64


index_primary                              name  index_ancillary Country
0              0.0                       Afghanistan              NaN     NaN
1              1.0                           Albania              NaN     NaN
2              2.0                           Algeria              NaN     NaN
3              3.0                    American Samoa              NaN     NaN
4              4.0                           Andorra              NaN     NaN
5              5.0                            Angola              NaN     NaN
6              6.0                          Anguilla              NaN     NaN
7              7.0               Antigua and Barbuda              NaN     NaN
10            10.0                             Aruba              NaN     NaN
16            16.0                        Bangladesh              NaN     NaN
17            17.0                          Barbados              NaN     NaN
20            20.0                            Belize              NaN     NaN
21            21.0                             Benin              NaN     NaN
23            23.0                            Bhutan              NaN     NaN
24            24.0                           Bolivia              NaN     NaN
25            25.0            Bosnia and Herzegovina              NaN     NaN
28            28.0            British Virgin Islands              NaN     NaN
29            29.0                            Brunei              NaN     NaN
32            32.0                           Burundi              NaN     NaN
33            33.0                          Cambodia              NaN     NaN
34            34.0                          Cameroon              NaN     NaN
36            36.0                        Cape Verde              NaN     NaN
37            37.0                    Cayman Islands              NaN     NaN
38            38.0          Central African Republic              NaN     NaN
39            39.0                              Chad              NaN     NaN
40            40.0                             Chile              NaN     NaN
43            43.0                           Comoros              NaN     NaN
44            44.0                      Cook Islands              NaN     NaN
45            45.0                        Costa Rica              NaN     NaN
48            48.0                           Curacao              NaN     NaN
49            49.0                            Cyprus              NaN     NaN
52            52.0                          Djibouti              NaN     NaN
53            53.0                          Dominica              NaN     NaN
55            55.0                          DR Congo              NaN     NaN
58            58.0                       El Salvador              NaN     NaN
59            59.0                 Equatorial Guinea              NaN     NaN
60            60.0                           Eritrea              NaN     NaN
62            62.0                          Eswatini              NaN     NaN
64            64.0                  Falkland Islands              NaN     NaN
65            65.0                     Faroe Islands              NaN     NaN
69            69.0                     French Guiana              NaN     NaN
70            70.0                  French Polynesia              NaN     NaN
71            71.0                             Gabon              NaN     NaN
72            72.0                            Gambia              NaN     NaN
76            76.0                         Gibraltar              NaN     NaN
78            78.0                         Greenland              NaN     NaN
80            80.0                        Guadeloupe              NaN     NaN
81            81.0                              Guam              NaN     NaN
82            82.0                         Guatemala              NaN     NaN
83            83.0                            Guinea              NaN     NaN
84            84.0         

From the above we see that now only a single entry from the `df_tokyo` is unmatched i.e. Kosovo. This is because `df_population` has no record for 'Kosovo'.

The remaining records from `df_population` which are not matching is because these countries did not participate in the Tokyo Olympic 2020 games.

In [66]:
df_tokyo

Country  Gold_Medal  Silver_Medal  Bronze_Medal  \
index_ancillary                                                               
0                         Argentina           0             1             2   
1                           Armenia           0             2             2   
2                         Australia          17             7            22   
3                           Austria           1             1             5   
4                        Azerbaijan           0             3             4   
5                           Bahamas           2             0             0   
6                           Bahrain           0             1             0   
7                           Belarus           1             3             3   
8                           Belgium           3             1             3   
9                           Bermuda           1             0             0   
10                         Botswana           0             0             1   
11                           Brazil           7             6             8   
12                         Bulgaria           3             1             2   
13                     Burkina Faso           0             0             1   
14                      Ivory Coast           0             0             1   
15                           Canada           7             6            11   
16                           Taiwan           2             4             6   
17                         Colombia           0             4             1   
18                          Croatia           3             3             2   
19                             Cuba           7             3             5   
20                   Czech Republic           4             4             3   
21                          Denmark           3             4             4   
22               Dominican Republic           0             3             2   
23                          Ecuador           2             1             0   
24                            Egypt           1             1             4   
25                          Estonia           1             0             1   
26                         Ethiopia           1             1             2   
27                             Fiji           1             0             1   
28                          Finland           0             0             2   
29                           France          10            12            11   
30                          Georgia           2             5             1   
31                          Germany          10            11            16   
32                            Ghana           0             0             1   
33                   United Kingdom          22            21            22   
34                           Greece           2             1             1   
35                          Grenada           0             0             1   
36                        Hong Kong           1             2             3   
37                          Hungary           6             7             7   
38                            India           1             2             4   
39                        Indonesia           1             1             3   
40                          Ireland           2             0             2   
41                             Iran           3             2             2   
42                           Israel           2             0             2   
43                            Italy          10            10            20   
44                          Jamaica           4             1             4   
45                            Japan          27            14            17   
46                           Jordan           0             1             1   
47                       Kazakhstan           0             0             8   
48                            Kenya           4             4             2   

In [67]:
del df_tmp

####  II. Match country names in `df_rio`:

In [68]:
df_tmp = find_divergence(df_rio, df_rio.columns[0])

df_tmp

index_primary        3
name                 3
index_ancillary    148
Country            148
dtype: int64


index_primary                              name  index_ancillary  \
0              0.0                       Afghanistan              NaN   
1              1.0                           Albania              NaN   
3              3.0                    American Samoa              NaN   
4              4.0                           Andorra              NaN   
5              5.0                            Angola              NaN   
6              6.0                          Anguilla              NaN   
7              7.0               Antigua and Barbuda              NaN   
10            10.0                             Aruba              NaN   
16            16.0                        Bangladesh              NaN   
17            17.0                          Barbados              NaN   
20            20.0                            Belize              NaN   
21            21.0                             Benin              NaN   
22            22.0                           Bermuda              NaN   
23            23.0                            Bhutan              NaN   
24            24.0                           Bolivia              NaN   
25            25.0            Bosnia and Herzegovina              NaN   
26            26.0                          Botswana              NaN   
28            28.0            British Virgin Islands              NaN   
29            29.0                            Brunei              NaN   
31            31.0                      Burkina Faso              NaN   
33            33.0                          Cambodia              NaN   
34            34.0                          Cameroon              NaN   
36            36.0                        Cape Verde              NaN   
37            37.0                    Cayman Islands              NaN   
38            38.0          Central African Republic              NaN   
39            39.0                              Chad              NaN   
40            40.0                             Chile              NaN   
43            43.0                           Comoros              NaN   
44            44.0                      Cook Islands              NaN   
45            45.0                        Costa Rica              NaN   
48            48.0                           Curacao              NaN   
49            49.0                            Cyprus              NaN   
52            52.0                          Djibouti              NaN   
53            53.0                          Dominica              NaN   
55            55.0                          DR Congo              NaN   
56            56.0                           Ecuador              NaN   
58            58.0                       El Salvador              NaN   
59            59.0                 Equatorial Guinea              NaN   
60            60.0                           Eritrea              NaN   
62            62.0                          Eswatini              NaN   
64            64.0                  Falkland Islands              NaN   
65            65.0                     Faroe Islands              NaN   
69            69.0                     French Guiana              NaN   
70            70.0                  French Polynesia              NaN   
71            71.0                             Gabon              NaN   
72            72.0                            Gambia              NaN   
75            75.0                             Ghana              NaN   
76            76.0                         Gibraltar              NaN   
78            78.0                         Greenland              NaN   
80            80.0                        Guadeloupe              NaN   
81            81.0                              Guam              NaN   
82            82.0                         Guatemala              NaN   
83            83.0                            Guinea              NaN   
84            84.0                     Guinea-Bissau           

We can see that only one associations could not found correctly:
* Cote d'Ivoire	-> Ivory Coast

So, first we apply the 'CnT-pad' associations and then correct the wrong values manually

In [69]:
# First copy the 'CnT-pad' column and then fix wrong values manually
df_tmp["pop_fixed"] = df_tmp["CnT-pad"].copy()

df_tmp.loc[232, 'pop_fixed'] = "Ivory Coast"

# Now put the obtained values back into the df_2 data frame with the correct indexes
index_tmp = df_tmp['index_ancillary'].dropna().astype(int)
names_tmp = df_tmp['pop_fixed'].dropna().values
df_rio.loc[index_tmp, df_rio.columns[0]] = names_tmp

df_tmp = filter_unmatched_index(df_population, df_rio,"name", df_rio.columns[0])
df_tmp

index_primary        2
name                 2
index_ancillary    147
Country            147
dtype: int64


index_primary                              name  index_ancillary  \
0              0.0                       Afghanistan              NaN   
1              1.0                           Albania              NaN   
3              3.0                    American Samoa              NaN   
4              4.0                           Andorra              NaN   
5              5.0                            Angola              NaN   
6              6.0                          Anguilla              NaN   
7              7.0               Antigua and Barbuda              NaN   
10            10.0                             Aruba              NaN   
16            16.0                        Bangladesh              NaN   
17            17.0                          Barbados              NaN   
20            20.0                            Belize              NaN   
21            21.0                             Benin              NaN   
22            22.0                           Bermuda              NaN   
23            23.0                            Bhutan              NaN   
24            24.0                           Bolivia              NaN   
25            25.0            Bosnia and Herzegovina              NaN   
26            26.0                          Botswana              NaN   
28            28.0            British Virgin Islands              NaN   
29            29.0                            Brunei              NaN   
31            31.0                      Burkina Faso              NaN   
33            33.0                          Cambodia              NaN   
34            34.0                          Cameroon              NaN   
36            36.0                        Cape Verde              NaN   
37            37.0                    Cayman Islands              NaN   
38            38.0          Central African Republic              NaN   
39            39.0                              Chad              NaN   
40            40.0                             Chile              NaN   
43            43.0                           Comoros              NaN   
44            44.0                      Cook Islands              NaN   
45            45.0                        Costa Rica              NaN   
48            48.0                           Curacao              NaN   
49            49.0                            Cyprus              NaN   
52            52.0                          Djibouti              NaN   
53            53.0                          Dominica              NaN   
55            55.0                          DR Congo              NaN   
56            56.0                           Ecuador              NaN   
58            58.0                       El Salvador              NaN   
59            59.0                 Equatorial Guinea              NaN   
60            60.0                           Eritrea              NaN   
62            62.0                          Eswatini              NaN   
64            64.0                  Falkland Islands              NaN   
65            65.0                     Faroe Islands              NaN   
69            69.0                     French Guiana              NaN   
70            70.0                  French Polynesia              NaN   
71            71.0                             Gabon              NaN   
72            72.0                            Gambia              NaN   
75            75.0                             Ghana              NaN   
76            76.0                         Gibraltar              NaN   
78            78.0                         Greenland              NaN   
80            80.0                        Guadeloupe              NaN   
81            81.0                              Guam              NaN   
82            82.0                         Guatemala              NaN   
83            83.0                            Guinea              NaN   
84            84.0                     Guinea-Bissau           

For the below records of `df_rio`, there is no records in `df_population`:
* Independent Olympic Athletes
* Kosovo

The remaining records from `df_population` which are not matching is because these countries did not participate in the Rio Olympic 2016 games.

In [70]:
df_rio

Country  Gold  Silver  Bronze  Total
index_ancillary                                                           
0                                     Algeria     0       2       0      2
1                                   Argentina     3       1       0      4
2                                     Armenia     1       3       0      4
3                                   Australia     8      11      10     19
4                                     Austria     0       0       1      0
5                                  Azerbaijan     1       7      10      8
6                                     Bahamas     1       0       1      1
7                                     Bahrain     1       1       0      2
8                                     Belarus     1       4       4      5
9                                     Belgium     2       2       2      4
10                                     Brazil     7       6       6     13
11                                   Bulgaria     0       1       2      1
12                                    Burundi     0       1       0      1
13                                     Canada     4       3      15      7
14                                      China    26      18      26     44
15                                   Colombia     3       2       3      5
16                                Ivory Coast     1       0       1      1
17                                    Croatia     5       3       2      8
18                                       Cuba     5       2       4      7
19                             Czech Republic     1       2       7      3
20                                    Denmark     2       6       7      8
21                         Dominican Republic     0       0       1      0
22                                      Egypt     0       0       3      0
23                                    Estonia     0       0       1      0
24                                   Ethiopia     1       2       5      3
25                                       Fiji     1       0       0      1
26                                    Finland     0       0       1      0
27                                     France    10      18      14     28
28                                    Georgia     2       1       4      3
29                                    Germany    17      10      15     27
30                                     Greece     3       1       2      4
31                                    Grenada     0       1       0      1
32                                    Hungary     8       3       4     11
33               Independent Olympic Athletes     1       0       1      1
34                                      India     0       1       1      1
35                                  Indonesia     1       2       0      3
36                                       Iran     3       1       4      4
37                                    Ireland     0       2       0      2
38                                     Israel     0       0       2      0
39                                      Italy     8      12       8     20
40                                    Jamaica     6       3       2      9
41                                      Japan    12       8      21     20
42                                     Jordan     1       0       0      1
43                                 Kazakhstan     3       5       9      8
44                                      Kenya     6       6       1     12
45                                     Kosovo     1       0       0      1
46                                  Lithuania     0       1       3      1
47                                   Malaysia     0       4       1      4
48                                     Mexico     0       3       2      3
49                                    Moldova     0       0       1      0
50                                   Mongolia     0       1       1      1
51                                    Morocco     0       0    

In [71]:
del df_tmp

#### III. Match country names in `df_london`:

In [72]:
df_tmp = find_divergence(df_london, df_london.columns[0])

df_tmp

index_primary        9
name                 9
index_ancillary    156
Country            156
dtype: int64


index_primary                              name  index_ancillary  \
1              1.0                           Albania              NaN   
3              3.0                    American Samoa              NaN   
4              4.0                           Andorra              NaN   
5              5.0                            Angola              NaN   
6              6.0                          Anguilla              NaN   
7              7.0               Antigua and Barbuda              NaN   
10            10.0                             Aruba              NaN   
12            12.0                           Austria              NaN   
16            16.0                        Bangladesh              NaN   
17            17.0                          Barbados              NaN   
20            20.0                            Belize              NaN   
21            21.0                             Benin              NaN   
22            22.0                           Bermuda              NaN   
23            23.0                            Bhutan              NaN   
24            24.0                           Bolivia              NaN   
25            25.0            Bosnia and Herzegovina              NaN   
28            28.0            British Virgin Islands              NaN   
29            29.0                            Brunei              NaN   
31            31.0                      Burkina Faso              NaN   
32            32.0                           Burundi              NaN   
33            33.0                          Cambodia              NaN   
36            36.0                        Cape Verde              NaN   
37            37.0                    Cayman Islands              NaN   
38            38.0          Central African Republic              NaN   
39            39.0                              Chad              NaN   
40            40.0                             Chile              NaN   
41            41.0                             China              NaN   
43            43.0                           Comoros              NaN   
44            44.0                      Cook Islands              NaN   
45            45.0                        Costa Rica              NaN   
48            48.0                           Curacao              NaN   
52            52.0                          Djibouti              NaN   
53            53.0                          Dominica              NaN   
55            55.0                          DR Congo              NaN   
56            56.0                           Ecuador              NaN   
58            58.0                       El Salvador              NaN   
59            59.0                 Equatorial Guinea              NaN   
60            60.0                           Eritrea              NaN   
62            62.0                          Eswatini              NaN   
64            64.0                  Falkland Islands              NaN   
65            65.0                     Faroe Islands              NaN   
66            66.0                              Fiji              NaN   
69            69.0                     French Guiana              NaN   
70            70.0                  French Polynesia              NaN   
72            72.0                            Gambia              NaN   
75            75.0                             Ghana              NaN   
76            76.0                         Gibraltar              NaN   
78            78.0                         Greenland              NaN   
80            80.0                        Guadeloupe              NaN   
81            81.0                              Guam              NaN   
83            83.0                            Guinea              NaN   
84            84.0                     Guinea-Bissau              NaN   
85            85.0                            Guyana              NaN   
86            86.0                             Haiti           

We can see that some associations have been correctly identified
* Hong Kong, China -> Hong Kong
* Russian Federation -> Russia	
* United States of America -> United States

And some associations could not found correctly:
* Chinese Taipei -> Taiwan
* Democratic People's Republic of Korea -> North Korea
* Great Britain	-> 	United Kingdom
* Islamic Republic of Iran -> Iran
* People's Republic of China -> China
* Republic of Korea	-> South Korea

So, first we apply the 'CnT-pad' associations and then correct the wrong values manually

In [73]:
# First copy the 'CnT-pad' column and then fix wrong values manually
df_tmp["pop_fixed"] = df_tmp["CnT-pad"].copy()

df_tmp.loc[232, 'pop_fixed'] = "Taiwan"
df_tmp.loc[233, 'pop_fixed'] = "North Korea"
df_tmp.loc[234, 'pop_fixed'] = "United Kingdom"
df_tmp.loc[236, 'pop_fixed'] = "Iran"
df_tmp.loc[237, 'pop_fixed'] = "China"
df_tmp.loc[238, 'pop_fixed'] = "South Korea"

# Now put the obtained values back into the df_2 data frame with the correct indexes
index_tmp = df_tmp['index_ancillary'].dropna().astype(int)
names_tmp = df_tmp['pop_fixed'].dropna().values
df_london.loc[index_tmp, df_london.columns[0]] = names_tmp

df_tmp = filter_unmatched_index(df_population, df_london,"name", df_london.columns[0])
df_tmp

index_primary        0
name                 0
index_ancillary    147
Country            147
dtype: int64


index_primary                              name  index_ancillary Country
1                1                           Albania              NaN     NaN
3                3                    American Samoa              NaN     NaN
4                4                           Andorra              NaN     NaN
5                5                            Angola              NaN     NaN
6                6                          Anguilla              NaN     NaN
7                7               Antigua and Barbuda              NaN     NaN
10              10                             Aruba              NaN     NaN
12              12                           Austria              NaN     NaN
16              16                        Bangladesh              NaN     NaN
17              17                          Barbados              NaN     NaN
20              20                            Belize              NaN     NaN
21              21                             Benin              NaN     NaN
22              22                           Bermuda              NaN     NaN
23              23                            Bhutan              NaN     NaN
24              24                           Bolivia              NaN     NaN
25              25            Bosnia and Herzegovina              NaN     NaN
28              28            British Virgin Islands              NaN     NaN
29              29                            Brunei              NaN     NaN
31              31                      Burkina Faso              NaN     NaN
32              32                           Burundi              NaN     NaN
33              33                          Cambodia              NaN     NaN
36              36                        Cape Verde              NaN     NaN
37              37                    Cayman Islands              NaN     NaN
38              38          Central African Republic              NaN     NaN
39              39                              Chad              NaN     NaN
40              40                             Chile              NaN     NaN
43              43                           Comoros              NaN     NaN
44              44                      Cook Islands              NaN     NaN
45              45                        Costa Rica              NaN     NaN
48              48                           Curacao              NaN     NaN
52              52                          Djibouti              NaN     NaN
53              53                          Dominica              NaN     NaN
55              55                          DR Congo              NaN     NaN
56              56                           Ecuador              NaN     NaN
58              58                       El Salvador              NaN     NaN
59              59                 Equatorial Guinea              NaN     NaN
60              60                           Eritrea              NaN     NaN
62              62                          Eswatini              NaN     NaN
64              64                  Falkland Islands              NaN     NaN
65              65                     Faroe Islands              NaN     NaN
66              66                              Fiji              NaN     NaN
69              69                     French Guiana              NaN     NaN
70              70                  French Polynesia              NaN     NaN
72              72                            Gambia              NaN     NaN
75              75                             Ghana              NaN     NaN
76              76                         Gibraltar              NaN     NaN
78              78                         Greenland              NaN     NaN
80              80                        Guadeloupe              NaN     NaN
81              81                              Guam              NaN     NaN
83              83                            Guinea              NaN     NaN
84              84         

The remaining records from `df_population` which are not matching is because these countries did not participate in the London Olympic 2012 games.

In [74]:
df_london

Country  Gold_Medal  Silver_Medal  Bronze_Medal  \
index_ancillary                                                                
0                        Afghanistan           0             0             1   
1                            Algeria           1             0             0   
2                          Argentina           1             1             2   
3                            Armenia           0             1             1   
4                          Australia           8            15            12   
5                         Azerbaijan           2             2             6   
6                            Bahamas           1             0             0   
7                            Bahrain           1             0             0   
8                            Belarus           2             5             3   
9                            Belgium           0             1             2   
10                          Botswana           0             1             0   
11                            Brazil           3             5             9   
12                          Bulgaria           0             2             1   
13                          Cameroon           0             0             1   
14                            Canada           2             5            11   
15                            Taiwan           1             0             1   
16                          Colombia           1             3             4   
17                           Croatia           3             1             2   
18                              Cuba           5             3             7   
19                            Cyprus           0             1             0   
20                    Czech Republic           4             3             4   
21                       North Korea           4             0             2   
22                           Denmark           2             4             3   
23                Dominican Republic           1             1             0   
24                             Egypt           0             3             1   
25                           Estonia           0             1             1   
26                          Ethiopia           3             2             2   
27                           Finland           0             2             1   
28                            France          11            11            13   
29                             Gabon           0             1             0   
30                           Georgia           1             2             3   
31                           Germany          11            20            13   
32                    United Kingdom          29            17            19   
33                            Greece           0             0             2   
34                           Grenada           1             0             0   
35                         Guatemala           0             1             0   
36                         Hong Kong           0             0             1   
37                           Hungary           8             4             6   
38                             India           0             2             4   
39                         Indonesia           0             2             1   
40                           Ireland           1             1             4   
41                              Iran           7             5             1   
42                             Italy           8             9            11   
43                           Jamaica           4             5             3   
44                             Japan           7            14            17   
45                        Kazakhstan           3             1             7   
46                             Kenya           2             4             7   
47                            Kuwait           0             0             1   
48                           

In [75]:
del df_tmp

####  IV. Match country names in `df_covid_vac`:

In [76]:
# get unique country name from the Covid_Vaccination table 
df = pd.DataFrame(df_covid_vac.location.unique(), columns=["Country_Name"])
df_tmp = find_divergence(df, df.columns[0])

df_tmp

index_primary      15
name               15
index_ancillary    23
Country_Name       23
dtype: int64


index_primary                          name  index_ancillary  \
3              3.0                American Samoa              NaN   
50            50.0                Czech Republic              NaN   
55            55.0                      DR Congo              NaN   
65            65.0                 Faroe Islands              NaN   
69            69.0                 French Guiana              NaN   
80            80.0                    Guadeloupe              NaN   
81            81.0                          Guam              NaN   
99            99.0                   Ivory Coast              NaN   
117          117.0                         Macau              NaN   
125          125.0                    Martinique              NaN   
128          128.0                       Mayotte              NaN   
149          149.0                   North Korea              NaN   
151          151.0      Northern Mariana Islands              NaN   
164          164.0                   Puerto Rico              NaN   
166          166.0         Republic of the Congo              NaN   
167          167.0                       Reunion              NaN   
171          171.0              Saint Barthelemy              NaN   
174          174.0                  Saint Martin              NaN   
175          175.0     Saint Pierre and Miquelon              NaN   
205          205.0                   Timor-Leste              NaN   
220          220.0  United States Virgin Islands              NaN   
224          224.0                  Vatican City              NaN   
228          228.0                Western Sahara              NaN   
232            NaN                           NaN             24.0   
233            NaN                           NaN             44.0   
234            NaN                           NaN             47.0   
235            NaN                           NaN             52.0   
236            NaN                           NaN             53.0   
237            NaN                           NaN             66.0   
238            NaN                           NaN             82.0   
239            NaN                           NaN            101.0   
240            NaN                           NaN            106.0   
241            NaN                           NaN            118.0   
242            NaN                           NaN            149.0   
243            NaN                           NaN            160.0   
244            NaN                           NaN            167.0   
245            NaN                           NaN            199.0   
246            NaN                           NaN            217.0   

                        Country_Name                          CnT-pad  \
3                                NaN                              NaN   
50                               NaN                              NaN   
55                               NaN                              NaN   
65                               NaN                              NaN   
69                               NaN                              NaN   
80                               NaN                              NaN   
81                               NaN                              NaN   
99                               NaN                              NaN   
117                              NaN                              NaN   
125                              NaN                              NaN   
128                              NaN                              NaN   
149                              NaN                              NaN   
151                              NaN                              NaN   
164                              NaN                              NaN   
166                              NaN                              NaN   
167                              NaN                              NaN   
171                              NaN                              NaN   

We can see that only one associations have been correctly identified
* Czechia -> Czech Republic

And some associations could not found correctly:
* Congo -> Republic of the Congo
* Cote d'Ivoire	-> Ivory Coast
* Democratic Republic of Congo -> DR Congo

And here were also some mistakes:
* Northern Cyprus -> Northern Mariana Islands
* Saint Helena	-> Saint Barthelemy

So, first we apply the 'CnT-pad' associations and then correct the wrong values manually

In [77]:
# First copy the 'CnT-pad' column and then fix wrong values manually
df_tmp["pop_fixed"] = df_tmp["CnT-pad"].copy()

df_tmp.loc[233, 'pop_fixed'] = "Republic of the Congo"
df_tmp.loc[234, 'pop_fixed'] = "Ivory Coast"
df_tmp.loc[236, 'pop_fixed'] = "DR Congo"
df_tmp.loc[242, 'pop_fixed'] = "Northern Cyprus"
df_tmp.loc[244, 'pop_fixed'] = "Saint Helena"


# Now put the obtained values back into the df_2 data frame with the correct indexes
index_tmp = df_tmp['index_ancillary'].dropna().astype(int)
names_tmp = df_tmp['pop_fixed'].dropna().values
df.loc[index_tmp, df.columns[0]] = names_tmp

df_tmp = filter_unmatched_index(df_population, df,"name", df.columns[0])
df_tmp

index_primary       7
name                7
index_ancillary    15
Country_Name       15
dtype: int64


index_primary                          name  index_ancillary  \
3              3.0                American Samoa              NaN   
69            69.0                 French Guiana              NaN   
80            80.0                    Guadeloupe              NaN   
81            81.0                          Guam              NaN   
125          125.0                    Martinique              NaN   
128          128.0                       Mayotte              NaN   
149          149.0                   North Korea              NaN   
151          151.0      Northern Mariana Islands              NaN   
164          164.0                   Puerto Rico              NaN   
167          167.0                       Reunion              NaN   
171          171.0              Saint Barthelemy              NaN   
174          174.0                  Saint Martin              NaN   
175          175.0     Saint Pierre and Miquelon              NaN   
220          220.0  United States Virgin Islands              NaN   
228          228.0                Western Sahara              NaN   
232            NaN                           NaN             24.0   
233            NaN                           NaN             82.0   
234            NaN                           NaN            101.0   
235            NaN                           NaN            106.0   
236            NaN                           NaN            149.0   
237            NaN                           NaN            160.0   
238            NaN                           NaN            167.0   

                        Country_Name  
3                                NaN  
69                               NaN  
80                               NaN  
81                               NaN  
125                              NaN  
128                              NaN  
149                              NaN  
151                              NaN  
164                              NaN  
167                              NaN  
171                              NaN  
174                              NaN  
175                              NaN  
220                              NaN  
228                              NaN  
232  Bonaire Sint Eustatius and Saba  
233                         Guernsey  
234                           Jersey  
235                           Kosovo  
236                  Northern Cyprus  
237                         Pitcairn  
238                     Saint Helena

The remaining records from `df_population` and `df_covid_vac` which are not matching is because these countries are not available in the other table respectively.


The following country name is different in `df_covid_vac`:

1. Congo -> Republic of the Congo
2. Cote d'Ivoire -> Ivory Coast
3. Democratic Republic of Congo -> DR Congo

So, we replace the country name in `df_covid_vac`.

In [78]:
old_val = ["Congo", "Cote d'Ivoire", "Democratic Republic of Congo"]
new_val = ["Republic of the Congo", "Ivory Coast", "DR Congo"]

df_covid_vac['location'] =  df_covid_vac['location'].replace(old_val,new_val)

In [79]:
df_covid_vac

location        date  total_cases  new_cases  total_deaths  \
0       Afghanistan  2020-02-24          5.0        5.0           0.0   
1       Afghanistan  2020-02-25          5.0        0.0           0.0   
2       Afghanistan  2020-02-26          5.0        0.0           0.0   
3       Afghanistan  2020-02-27          5.0        0.0           0.0   
4       Afghanistan  2020-02-28          5.0        0.0           0.0   
...             ...         ...          ...        ...           ...   
134875     Zimbabwe  2021-11-17     133557.0       52.0        4699.0   
134876     Zimbabwe  2021-11-18     133593.0       36.0        4699.0   
134877     Zimbabwe  2021-11-19     133593.0        0.0        4699.0   
134878     Zimbabwe  2021-11-20     133615.0       22.0        4699.0   
134879     Zimbabwe  2021-11-21     133647.0       32.0        4699.0   

        new_deaths  people_vaccinated  people_fully_vaccinated  
0              0.0                0.0                      0.0  
1              0.0                0.0                      0.0  
2              0.0                0.0                      0.0  
3              0.0                0.0                      0.0  
4              0.0                0.0                      0.0  
...            ...                ...                      ...  
134875         1.0                0.0                      0.0  
134876         0.0          3583256.0                2727175.0  
134877         0.0          3625221.0                2737278.0  
134878         0.0          3651820.0                2744192.0  
134879         0.0          3672011.0                2747693.0  

[126276 rows x 8 columns]

In [80]:
del df, df_tmp

#### V. Match country names in `df_gdp`:

In [81]:
df_tmp = find_divergence(df_gdp, df_gdp.columns[0])

df_tmp

index_primary      23
name               23
index_ancillary    58
Country            58
dtype: int64


index_primary                          name  index_ancillary  \
3              3.0                American Samoa              NaN   
6              6.0                      Anguilla              NaN   
14            14.0                       Bahamas              NaN   
22            22.0                       Bermuda              NaN   
28            28.0        British Virgin Islands              NaN   
29            29.0                        Brunei              NaN   
36            36.0                    Cape Verde              NaN   
37            37.0                Cayman Islands              NaN   
41            41.0                         China              NaN   
44            44.0                  Cook Islands              NaN   
47            47.0                          Cuba              NaN   
48            48.0                       Curacao              NaN   
55            55.0                      DR Congo              NaN   
64            64.0              Falkland Islands              NaN   
65            65.0                 Faroe Islands              NaN   
69            69.0                 French Guiana              NaN   
70            70.0              French Polynesia              NaN   
72            72.0                        Gambia              NaN   
76            76.0                     Gibraltar              NaN   
78            78.0                     Greenland              NaN   
80            80.0                    Guadeloupe              NaN   
81            81.0                          Guam              NaN   
88            88.0                     Hong Kong              NaN   
96            96.0                   Isle of Man              NaN   
99            99.0                   Ivory Coast              NaN   
107          107.0                    Kyrgyzstan              NaN   
108          108.0                          Laos              NaN   
114          114.0                 Liechtenstein              NaN   
117          117.0                         Macau              NaN   
125          125.0                    Martinique              NaN   
128          128.0                       Mayotte              NaN   
130          130.0                    Micronesia              NaN   
132          132.0                        Monaco              NaN   
135          135.0                    Montserrat              NaN   
143          143.0                 New Caledonia              NaN   
148          148.0                          Niue              NaN   
149          149.0                   North Korea              NaN   
150          150.0               North Macedonia              NaN   
151          151.0      Northern Mariana Islands              NaN   
156          156.0                     Palestine              NaN   
166          166.0         Republic of the Congo              NaN   
167          167.0                       Reunion              NaN   
169          169.0                        Russia              NaN   
171          171.0              Saint Barthelemy              NaN   
174          174.0                  Saint Martin              NaN   
175          175.0     Saint Pierre and Miquelon              NaN   
179          179.0         Sao Tome and Principe              NaN   
186          186.0                  Sint Maarten              NaN   
187          187.0                      Slovakia              NaN   
192          192.0                   South Korea              NaN   
193          193.0                   South Sudan              NaN   
201          201.0                        Taiwan              NaN   
207          207.0                       Tokelau              NaN   
213          213.0      Turks and Caicos Islands              NaN   
220          220.0  United States Virgin Islands              NaN   
224          224.0                  Vatican City              NaN   
227          227.0             Wallis and Futuna              NaN   
228

We can see that some associations have been correctly identified
* Bahamas, The -> Bahamas
* Brunei Darussalam	-> Brunei	
* Cabo Verde -> Cape Verde
* Congo, Republic of -> Republic of the Congo
* Gambia, The -> Gambia	
* Hong Kong SAR	-> Hong Kong
* Macao -> SAR	Macau
* Micronesia, Fed. States of -> Micronesia
* Russian Federation -> Russia
* Slovak Republic -> Slovakia	
* South Sudan, Republic of	-> South Sudan
* So Tom and Prncipe ->	Sao Tome and Principe	

And some associations could not found:
* China, People's Republic of -> China
* Congo, Dem. Rep. of the -> DR Congo
* Cte d'Ivoire	-> 	Ivory Coast
* Korea, Republic of -> South Korea
* Kyrgyz Republic	-> Kyrgyzstan
* Lao P.D.R. -> Laos
* Taiwan Province of China -> Taiwan

And here were also many mistakes.
* West Bank and Gaza -> Western Sahara	
* Africa -> American Samoa


So, first we apply the 'CnT-pad' associations and then correct the wrong values manually

In [82]:
# First copy the 'CnT-pad' column and then fix wrong values manually
df_tmp["pop_fixed"] = df_tmp["CnT-pad"].copy()

df_tmp.loc[235, 'pop_fixed'] = 'China'
df_tmp.loc[236, 'pop_fixed'] = "DR Congo"
df_tmp.loc[238, 'pop_fixed'] = "Ivory Coast"
df_tmp.loc[241, 'pop_fixed'] = "South Korea"
df_tmp.loc[243, 'pop_fixed'] = 'Kyrgyzstan'
df_tmp.loc[244, 'pop_fixed'] = 'Laos'
df_tmp.loc[252, 'pop_fixed'] = "Taiwan"

df_tmp.loc[253, 'pop_fixed'] = "West Bank and Gaza"
df_tmp.loc[254, 'pop_fixed'] = "Africa"

# Now put the obtained values back into the df_2 table with the correct indexes
index_tmp = df_tmp['index_ancillary'].dropna().astype(int)
names_tmp = df_tmp['pop_fixed'].dropna().values
df_gdp.loc[index_tmp, df_gdp.columns[0]] = names_tmp

df_tmp = filter_unmatched_index(df_population, df_gdp,"name", df_gdp.columns[0])
df_tmp

index_primary       3
name                3
index_ancillary    38
Country            38
dtype: int64


index_primary                          name  index_ancillary  \
3              3.0                American Samoa              NaN   
6              6.0                      Anguilla              NaN   
22            22.0                       Bermuda              NaN   
28            28.0        British Virgin Islands              NaN   
37            37.0                Cayman Islands              NaN   
44            44.0                  Cook Islands              NaN   
47            47.0                          Cuba              NaN   
48            48.0                       Curacao              NaN   
64            64.0              Falkland Islands              NaN   
65            65.0                 Faroe Islands              NaN   
69            69.0                 French Guiana              NaN   
70            70.0              French Polynesia              NaN   
76            76.0                     Gibraltar              NaN   
78            78.0                     Greenland              NaN   
80            80.0                    Guadeloupe              NaN   
81            81.0                          Guam              NaN   
96            96.0                   Isle of Man              NaN   
114          114.0                 Liechtenstein              NaN   
125          125.0                    Martinique              NaN   
128          128.0                       Mayotte              NaN   
132          132.0                        Monaco              NaN   
135          135.0                    Montserrat              NaN   
143          143.0                 New Caledonia              NaN   
148          148.0                          Niue              NaN   
149          149.0                   North Korea              NaN   
151          151.0      Northern Mariana Islands              NaN   
156          156.0                     Palestine              NaN   
167          167.0                       Reunion              NaN   
171          171.0              Saint Barthelemy              NaN   
174          174.0                  Saint Martin              NaN   
175          175.0     Saint Pierre and Miquelon              NaN   
186          186.0                  Sint Maarten              NaN   
207          207.0                       Tokelau              NaN   
213          213.0      Turks and Caicos Islands              NaN   
220          220.0  United States Virgin Islands              NaN   
224          224.0                  Vatican City              NaN   
227          227.0             Wallis and Futuna              NaN   
228          228.0                Western Sahara              NaN   
232            NaN                           NaN             92.0   
233            NaN                           NaN            193.0   
234            NaN                           NaN            197.0   

                Country  
3                   NaN  
6                   NaN  
22                  NaN  
28                  NaN  
37                  NaN  
44                  NaN  
47                  NaN  
48                  NaN  
64                  NaN  
65                  NaN  
69                  NaN  
70                  NaN  
76                  NaN  
78                  NaN  
80                  NaN  
81                  NaN  
96                  NaN  
114                 NaN  
125                 NaN  
128                 NaN  
132                 NaN  
135                 NaN  
143                 NaN  
148                 NaN  
149                 NaN  
151                 NaN  
156                 NaN  
167                 NaN  
171                 NaN  
174                 NaN  
175                 NaN  
186                 NaN  
207                 NaN  
213                 NaN  
220                 NaN  
224                 NaN  
227                 NaN  
228                 NaN  
232              Kosovo  
233  West Bank and Gaza  
234              Africa

The remaining records from `df_population` and `df_gdp` which are not matching is because these countries are not available in the other table respectively.

In [83]:
df_gdp

Country      2012       2013  \
index_ancillary                                                          
1                                     Afghanistan    20.293      20.17   
2                                         Albania    12.324     12.784   
3                                         Algeria   209.059    209.755   
4                                         Andorra     3.189      3.193   
5                                          Angola   128.053     136.71   
6                             Antigua and Barbuda       1.2      1.181   
7                                       Argentina   579.666    611.471   
8                                         Armenia    10.619     11.121   
9                                           Aruba     2.615      2.728   
10                                      Australia  1569.311   1518.426   
11                                        Austria   409.661    430.197   
12                                     Azerbaijan    69.687      74.16   
13                                        Bahamas     10.72     10.495   
14                                        Bahrain    30.749     32.539   
15                                     Bangladesh   133.304    150.026   
16                                       Barbados      4.61      4.677   
17                                        Belarus    65.669     75.496   
18                                        Belgium   496.467    521.799   
19                                         Belize     1.523      1.579   
20                                          Benin    11.148     12.518   
21                                         Bhutan     1.772      1.805   
22                                        Bolivia    27.282     30.883   
23                         Bosnia and Herzegovina    17.207     18.155   
24                                       Botswana    15.519     14.368   
25                                         Brazil  2464.054   2471.718   
26                                         Brunei    19.047     18.092   
27                                       Bulgaria    54.031     55.617   
28                                   Burkina Faso    12.569     13.444   
29                                        Burundi     2.333      2.456   
30                                     Cape Verde     1.742       1.85   
31                                       Cambodia    14.057     15.228   
32                                       Cameroon    29.121     32.358   
33                                         Canada  1828.362   1846.595   
34                       Central African Republic     2.512      1.692   
35                                           Chad    12.411     12.994   
36                                          Chile   267.021    278.347   
37                                          China  8539.584   9624.928   
38                                       Colombia   370.691    382.093   
39                                        Comoros     1.016      1.116   
40                                       DR Congo     29.35     32.695   
41                          Republic of the Congo    17.704     17.959   
42                                     Costa Rica    47.231     50.949   
43                                        Croatia    56.581     58.194   
44                                         Cyprus    24.993       23.9   
45                                 Czech Republic   208.858    211.686   
46                                    Ivory Coast     37.03     43.228   
47                                        Denmark   327.149    343.584   
48                                       Djibouti       1.9      2.043   
49                                       Dominica     0.486      0.498   
50                             Dominican Republic    60.747     62.758   
51                                        Ecuador    87.925      95.13   
52                                          Egypt   278.769    288.007   
53                                    El Salva

In [84]:
del df_tmp

---

#### Now, we have completed our data pre-processing for all the datasets and the data is now ready to be loaded into a **_SQL Database_**

---
---

## 3. Store the datasets in SQL Database Server

To store the cleaned data in a SQL database server, we perform the following steps:
1. login and establish connection to a database.
2. create all the required tables with the appropriate data types.
3. store the data in the database server.

### Connect and login into MySQL database server

In [85]:
import mysql.connector
from getpass import getpass

In [86]:
connection = mysql.connector.connect(user=input("Enter username: "), password=getpass("Enter password: ")) 

cursor = connection.cursor()

Enter username: root
Enter password: ········


### Create and Select Database

In [87]:
# Create Database "olympic"

create_db_query = "CREATE DATABASE IF NOT EXISTS olympic"

cursor.execute(create_db_query)

In [88]:
# Check if database is created or not

show_db_query = "SHOW DATABASES"
cursor.execute(show_db_query)

for db in cursor:
    print(db)


('birthdate_db',)
('covid_2020',)
('covid_2021',)
('information_schema',)
('mysql',)
('olympic',)
('performance_schema',)
('sys',)


In [89]:
select_db_query = "use olympic"
cursor.execute(select_db_query)

### Create Tables

In [90]:
tables_def = {
"tokyo_olympic_2020" : """
                        CREATE TABLE IF NOT EXISTS tokyo_olympic_2020 (
                            country_name VARCHAR(60) NOT NULL,
                            gold_medals INT NOT NULL,
                            silver_medals INT NOT NULL,
                            bronze_medals INT NOT NULL,
                            total_medals INT NOT NULL,

                            CONSTRAINT uniq_constraint UNIQUE(country_name)
                        )
                    """,

"rio_olympic_2016" : """
                        CREATE TABLE IF NOT EXISTS rio_olympic_2016 (
                            country_name VARCHAR(60) NOT NULL,
                            gold_medals INT NOT NULL,
                            silver_medals INT NOT NULL,
                            bronze_medals INT NOT NULL,
                            total_medals INT NOT NULL,

                            CONSTRAINT uniq_constraint UNIQUE(country_name)
                        )
                """,

"london_olympic_2012" : """
                        CREATE TABLE IF NOT EXISTS london_olympic_2012 (
                            country_name VARCHAR(60) NOT NULL,
                            gold_medals INT NOT NULL,
                            silver_medals INT NOT NULL,
                            bronze_medals INT NOT NULL,
                            total_medals INT NOT NULL,
                            
                            CONSTRAINT uniq_constraint UNIQUE(country_name)
                        )
                        """,

"population" : """
                CREATE TABLE IF NOT EXISTS population (
                    country_name VARCHAR(60) NOT NULL,
                    pop_2020 INT UNSIGNED NOT NULL,
                    pop_2021 INT UNSIGNED NOT NULL,
                    
                    CONSTRAINT uniq_constraint UNIQUE(country_name)
                )
            """,

"covid_and_vac" : """
                    CREATE TABLE IF NOT EXISTS covid_and_vac (
                        country_name VARCHAR(60) NOT NULL,
                        date_reported DATE NOT NULL,
                        cumulative_cases INT UNSIGNED NOT NULL,
                        new_cases INT NOT NULL,
                        cumulative_deaths INT UNSIGNED NOT NULL,
                        new_deaths INT NOT NULL,
                        people_vaccinated INT UNSIGNED NOT NULL,
                        people_fully_vaccinated INT UNSIGNED NOT NULL,
                        
                        
                        CONSTRAINT uniq_constraint UNIQUE(country_name, date_reported)
                    )
                """,

"gdp_value" : """
                CREATE TABLE IF NOT EXISTS gdp_value (
                    country_name VARCHAR(60) NOT NULL,
                    gdp_2012 FLOAT NOT NULL,
                    gdp_2013 FLOAT NOT NULL,
                    gdp_2014 FLOAT NOT NULL,
                    gdp_2015 FLOAT NOT NULL,
                    gdp_2016 FLOAT NOT NULL,
                    gdp_2017 FLOAT NOT NULL,
                    gdp_2018 FLOAT NOT NULL,
                    gdp_2019 FLOAT NOT NULL,
                    gdp_2020 FLOAT NOT NULL,
                    gdp_2021 FLOAT NOT NULL,
                    
                    CONSTRAINT uniq_constraint UNIQUE(country_name)
                )
            """
}

In [91]:
# Create all the tables in the database
for query in tables_def.values():
    cursor.execute(query)

In [92]:
# Show the created tables

show_tbl_query = "SHOW TABLES"
cursor.execute(show_tbl_query)

for tbl in cursor:
    print(tbl)

('covid_and_vac',)
('gdp_value',)
('london_olympic_2012',)
('population',)
('rio_olympic_2016',)
('tokyo_olympic_2020',)


---

### Write the data into the database



In [93]:
for i, row in df_tokyo.iterrows():
    sql = "INSERT INTO tokyo_olympic_2020 (country_name, gold_medals, silver_medals, \
    bronze_medals, total_medals) VALUES (%s,%s,%s,%s,%s)"
    
    cursor.execute(sql,tuple(row))
    
    connection.commit()

In [94]:
for i, row in df_rio.iterrows():
    sql = "INSERT INTO rio_olympic_2016 (country_name, gold_medals, silver_medals, \
    bronze_medals, total_medals) VALUES (%s,%s,%s,%s,%s)"

    cursor.execute(sql,tuple(row))

    connection.commit()

In [95]:
for i, row in df_london.iterrows():
    sql = "INSERT INTO london_olympic_2012 (country_name, gold_medals, silver_medals, \
    bronze_medals, total_medals) VALUES (%s,%s,%s,%s,%s)"

    cursor.execute(sql,tuple(row))

    connection.commit()

In [96]:
for i, row in df_population.iterrows():
    sql = "INSERT INTO population (country_name, pop_2020, pop_2021) VALUES (%s,%s,%s)"

    cursor.execute(sql,tuple(row))

    connection.commit()

In [97]:
for i, row in df_covid_vac.iterrows():
    sql = "INSERT INTO covid_and_vac (country_name, date_reported, cumulative_cases, new_cases, \
    cumulative_deaths, new_deaths, people_vaccinated, people_fully_vaccinated) \
    VALUES (%s,%s,%s,%s,%s,%s,%s,%s)"

    cursor.execute(sql,tuple(row))

    connection.commit()

In [98]:
for i, row in df_gdp.iterrows():
    sql = "INSERT INTO gdp_value (country_name, gdp_2012, gdp_2013, gdp_2014, \
    gdp_2015, gdp_2016, gdp_2017, gdp_2018, gdp_2019, gdp_2020, gdp_2021) \
    VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)"

    cursor.execute(sql,tuple(row))

    connection.commit()

---
---

### Close the database connection

Finally, we close the database connections.

In [99]:
# Close the database connections
cursor.close()
connection.close()